In [217]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings('ignore')

In [218]:
# Read the data using pandas and make a copy
df = pd.read_csv('../datasets/views/2020/data-us-2020.csv', na_values='?', comment = '\t', sep=',', skipinitialspace=True)

data = df.copy()

# Dropping Country column as it is all US data in this file
data.drop(['Country'], axis=1, inplace=True)

In [219]:
data.sample(15)

ConvertedComp  EdLevel  YearsCode  YearsCodePro
5428       237000.0        5         20            13
3462        55000.0        5         11             8
7663       250000.0        5         38            32
3841       240000.0        5         13             7
5358        95000.0        5         19             4
8189        50000.0        5          0             0
5388       600000.0        5         20            16
7587        60000.0        5         36             3
728        120000.0        5          5             3
2014       113000.0        6          8             5
3899       129000.0        6         13             3
6355       143000.0        5         24            24
1475       315000.0        6          7             4
5204       100000.0        5         18             9
2572        46000.0        8          9             9

In [220]:
# Creating the features matrix
X = data.drop('ConvertedComp', axis=1)

# Creating the labels
y = data['ConvertedComp']

In [221]:
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor

In [222]:

# splitting into training and testing data (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [223]:
# Fitting the model to the data
model = RandomForestRegressor(n_estimators=130)
model.fit(X_train, y_train);
model.score(X_test, y_test)

0.06450890253049724

In [224]:
app_test = model.predict([[1,1,1]])
app_test

array([52167.05586081])

In [225]:
# Making a prediction
# y_label = regr.predict(np.array([0, 2, 3, 4]))

In [226]:
y_preds = model.predict(X_test)
y_preds

array([112180.05345134, 147707.96703297, 241649.78493728, ...,
       109157.07076033,  87883.46923077,  99762.88119148])

In [227]:
y_test

2684    150000.0
6383    105000.0
5891    180000.0
6358    140000.0
5374     72000.0
          ...   
88       85000.0
734     120000.0
196     150000.0
7652     70000.0
3002     54000.0
Name: ConvertedComp, Length: 1670, dtype: float64

In [228]:
# Evaluating this model on the training data and the test data
model.score(X_train, y_train)

0.480003741472652

In [229]:
model.score(X_test, y_test)

0.06450890253049724

In [230]:
random_forest_regressor_results = '{:.2f}'.format(model.score(X_test, y_test) * 100)

In [231]:
np.random.seed(42)
for i in range(10, 200, 10):
    print(f'Trying model with {i} estimators...')
    model = RandomForestRegressor(n_estimators=i).fit(X_train, y_train)
    print(f'Model accuracy on test set: {model.score(X_test, y_test) * 100}%')
    print(' ')

Trying model with 10 estimators...
Model accuracy on test set: 1.6084603066399583%
 
Trying model with 20 estimators...
Model accuracy on test set: 5.418700186716374%
 
Trying model with 30 estimators...
Model accuracy on test set: 4.175144600452652%
 
Trying model with 40 estimators...
Model accuracy on test set: 6.4760175070528785%
 
Trying model with 50 estimators...
Model accuracy on test set: 6.453339986167739%
 
Trying model with 60 estimators...
Model accuracy on test set: 5.58218181541863%
 
Trying model with 70 estimators...
Model accuracy on test set: 5.850301999750885%
 
Trying model with 80 estimators...
Model accuracy on test set: 5.595028883899744%
 
Trying model with 90 estimators...
Model accuracy on test set: 6.306602306365006%
 
Trying model with 100 estimators...
Model accuracy on test set: 7.112772327980165%
 
Trying model with 110 estimators...
Model accuracy on test set: 6.335937201862507%
 
Trying model with 120 estimators...
Model accuracy on test set: 6.1790571

# Working with different estimators

In [232]:
# ml map shows to try lasso or elasticnet if few features are important
from sklearn import linear_model

np.random.seed(42)

# Creating the features matrix
X = data.drop('ConvertedComp', axis=1)

# Creating the labels
y = data['ConvertedComp']

# splitting into training and testing data (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# instantiate Lasso
lassoreg = linear_model.Lasso(normalize=True)
lassoreg.fit(X_train, y_train);

lasso_results = '{:.2f}'.format(lassoreg.score(X_test, y_test) * 100)
# Default calculates to a score of 17.644
#normalize=True improved score to 17.654
lassoreg.score(X_test, y_test) * 100

17.65440771812412

In [233]:
from sklearn.linear_model import ElasticNet
from sklearn.datasets import make_regression

np.random.seed(42)

# Creating the features matrix
X = data.drop('ConvertedComp', axis=1)

# Creating the labels
y = data['ConvertedComp']

# splitting into training and testing data (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model2 = ElasticNet(alpha=0.2)
model2.fit(X_train, y_train)

elasticnet_results = '{:.2f}'.format(model2.score(X_test, y_test) * 100)
# Default calculates to a score of 17.533
# alpha of 0.2 increased score to 17.6559; max_iter, l1_ration no gains; fit_intercept, normalize decreased score
model2.score(X_test, y_test)

0.17655903549086893

### ml map shows to try ridgeregression or SVR kernel linear if few features are important

In [234]:
# RidgeRegression
from sklearn.linear_model import Ridge

np.random.seed(42)

# Creating the features matrix
X = data.drop('ConvertedComp', axis=1)

# Creating the labels
y = data['ConvertedComp']

# splitting into training and testing data (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# instantiate Ridge
regr3 = Ridge()
regr3.fit(X_train, y_train)


ridge_results = '{:.2f}'.format(regr3.score(X_test, y_test) * 100)
# Default calculates to a score of 17.644
#normalize=True, fit_intercept=False decreased score, tol no impact
regr3.score(X_test, y_test)

0.1764423461756297

In [235]:
# SVR kernel='linear'
from sklearn import svm

np.random.seed(42)

# Creating the features matrix
X = data.drop('ConvertedComp', axis=1)

# Creating the labels
y = data['ConvertedComp']

# splitting into training and testing data (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# instantiate Support Vector Machines (SVM)
svr_linear = svm.SVR(kernel='linear')
svr_linear.fit(X_train, y_train)

svrkernellinear_results = '{:.2f}'.format(svr_linear.score(X_test, y_test) * 100)
svr_linear.score(X_test, y_test)

0.14014883948079182

In [236]:
# ml map shows to try SVR kernel rbf or ensembleregressors if nothing else worked

In [237]:
# SVR kernel='rbf'
from sklearn import svm

np.random.seed(42)

# Creating the features matrix
X = data.drop('ConvertedComp', axis=1)

# Creating the labels
y = data['ConvertedComp']

# splitting into training and testing data (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# instantiate Random Forest Regressor
svr_rbf = svm.SVR(kernel='rbf')
svr_rbf.fit(X_train, y_train)

svrkernelrbf_results = '{:.2f}'.format(svr_rbf.score(X_test, y_test) * 100)
svr_rbf.score(X_test, y_test)

-0.018659878833494847

In [238]:
# EnsembleRegressors
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

# Creating the features matrix
X = data.drop('ConvertedComp', axis=1)

# Creating the labels
y = data['ConvertedComp']

# splitting into training and testing data (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# instantiate Random Forest Regressor
rf = RandomForestRegressor()
rf.fit(X_train, y_train)

rf_results = '{:.2f}'.format(rf.score(X_test, y_test) * 100)
rf.score(X_test, y_test)

0.062172198735375606

In [239]:
from sklearn.linear_model import LinearRegression

np.random.seed(42)

# Creating the features matrix
X = data.drop('ConvertedComp', axis=1)

# Creating the labels
y = data['ConvertedComp']

# splitting into training and testing data (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# instantiate Random Forest Regressor
lreg = LinearRegression()
lreg.fit(X_train, y_train)

lreg_results = '{:.2f}'.format(lreg.score(X_test, y_test) * 100)
# Default calculates to a score of 17.644
# fit_intercept decreased score, normalize had no impact
lreg.score(X_test, y_test)

0.176441938103564

In [240]:
# trying svc linear classification
from sklearn import svm

np.random.seed(42)

# Creating the features matrix
X = data.drop('ConvertedComp', axis=1)

# Creating the labels
y = data['ConvertedComp']

# splitting into training and testing data (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# instantiate Random Forest Regressor
svcc = svm.SVC()
svcc.fit(X_train, y_train)

svcc.score(X_test, y_test)
svc_linear_classification_results = '{:.2f}'.format(svcc.score(X_test, y_test) * 100)

In [241]:
svcc.predict([[4, 10, 10]])

array([120000.])

In [242]:
svcc.predict([[1, 3, 3]])

array([75000.])

# Ranked results of the above estimators

In [243]:
print('Ranked Results based on score of test set:')
print(f'Elastic Net: {elasticnet_results}%')
print(f'Lasso: {lasso_results}%')
print(f'Ridge: {ridge_results}%')
print(f'Linear Regression: {lreg_results}%')
print(f'SVR Linear: {svrkernellinear_results}%')
print(f'SVC Linear Classification: {svc_linear_classification_results}%')
print(f'Random Forest Regressor: {random_forest_regressor_results}%')
print(f'Random Forest Regressor run 2: {rf_results}%')

print(f'SVR Kernel "rbf": {svrkernelrbf_results}%')



Ranked Results based on score of test set:
Elastic Net: 17.66%
Lasso: 17.65%
Ridge: 17.64%
Linear Regression: 17.64%
SVR Linear: 14.01%
SVC Linear Classification: 4.25%
Random Forest Regressor: 6.45%
Random Forest Regressor run 2: 6.22%
SVR Kernel "rbf": -1.87%


In [244]:
import pickle

pickle.dump(model2, open('model2.pkl', 'wb'))

In [245]:
loaded_model = pickle.load(open('model2.pkl', 'rb'))
loaded_model.score(X_test, y_test)

0.17655903549086893

In [246]:
model2.predict([[0, 0, 0]])

array([50450.69085167])